# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3eb5930e69acdd37b418e81fad0be055"
name = "PowerBox"
handle = "powerbox-2"
application_url = "https://speaker-promptly-amplifier-dial.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo1-demo.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,read_themes,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://speaker-promptly-amplifier-dial.trycloudflare.com/auth/callback",
  "https://speaker-promptly-amplifier-dial.trycloudflare.com/auth/shopify/callback",
  "https://speaker-promptly-amplifier-dial.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
