# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "988dfbed3a92c9eda0bc61a3917d6829"
name = "PowerBox Test"
handle = "powerbox-test-1"
application_url = "https://paypal-efficiently-segment-individually.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "powerboxtest.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_products,read_themes,write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [
  "https://paypal-efficiently-segment-individually.trycloudflare.com/auth/callback",
  "https://paypal-efficiently-segment-individually.trycloudflare.com/auth/shopify/callback",
  "https://paypal-efficiently-segment-individually.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
